damianavila/RISE

- livereveal/main.css
- livereveal/main.js
- livereveal/reset_reveal.css
Fixes #46
It takes me a few hours to make it work despite the minimal changes... surgical fixes :wink:
pinging @twiecki and @mwiebe who are involved in the bug report...
Sorry to take to much time to fix it... master was really change it and now that 3.0 is coming soon is more stable to deal with...
> Make RISE to work with Jupyter master again

- README.md
- livereveal/main.js
Kind of buggy, and sometime hard to change slides, but it works.
> allow use of leap motion

- livereveal/main.js
> Fix warnings from jshint

- livereveal/main.css
- livereveal/main.js
Instead of forcefully hiding note cells, add them to a class that's hidden during slideshow mode.
Closes gh-58
> Bring notes back when leaving slideshow mode

- livereveal/main.css
- livereveal/main.js
> Fix scrolling and go to the top on slide change

- livereveal/reset_reveal.css
As usual, a css conflict between IPython and reveal.js, je je...
closes #47
> Fix css conflict with dropdown widget

- livereveal/main.css
I've been annoyed by #39 as well...
> Hide the cell toolbar in presentations (Fixes #39)

- README.md
As promised, some usage notes!
OK that I added a 'usage' section?
> DOC: add some usage notes

- README.md
- livereveal/main.js
In order to set the `width` of the slides (some beamer at work have only a low resolution), I made it and some other options configurabe like `theme`, `transition`and `start_slideshow_at`
> Make more options configurable

- livereveal/main.css
> Fix ovewflow-y issue in markdown cells.

- README.md
- livereveal/main.js
> Fix shift-enter shortcut when you exit the presentation mode

- livereveal/main.js
Closes #37, it belongs to my old custom theme...
> Remove button_rise

- livereveal/main.css
- livereveal/main.js
> Workaround to fix the annoying higher heights on cells after exiting

- README.md
- livereveal/main.js
Tested by 3 of us... seems to work OK.
Closes #117
> Fix firefox

- livereveal/main.js
Also making config possible without restarting the server.
This should close: #172 and #194
> Fix custom config things

- MANIFEST.in
- README.md
- conda.recipe/meta.yaml
- conda.recipe/pre-unlink.sh
- rise/_version.py
- setup.cfg
On top of previous PRs.
Need to add a changelog yet...
Need to update README to reflect the changes...
> Prepare 4.0.0 beta release

- README.md
closes issue https://github.com/damianavila/RISE/issues/245
> solves #245

- rise/static/main.js
followup for #102 
before exiting reveal mode, this patch computes
the notebook index of the first cell in the currently displayed slide
that cell then gets selected and focused when returning to normal
notebook mode
this first attempt implements this behaviour unconditionally,
i.e. regardless of `start_slideshow_at`
I am not convinced that it should depend on that setting anyway
point being that it is rather straightforward to go to the beginning or end 
of the presentation when in normal notebook mode, and generally not critical 
this is of course open to further discussion though
> a rough implementation of enhancement described in #102

- conda.recipe/meta.yaml
- rise/_version.py
- rise/static/main.css
- rise/static/main.js
- rise/static/reveal.js/js/reveal.js
- setup.py
- src/less/main.less
Fix issue with key and black background (upstream issue) and add a reference for fullscreen view in the help.
Closes #105 and #158
> Fullscreen fixes

- conda.recipe/meta.yaml
- rise/static/main.css
- rise/static/main.js
- rise/static/reset_reveal.css
- rise/static/reveal.js/js/reveal.js
- setup.py
- src/less/main.less
This is on top of #256 
See last commit for the real changes.
Closes #129
> Fix cutoff

- README.md
I'm not sure if you want these here, but I thought I'd offer it and let you decide.
> Add Julia installation instructions

- rise/static/main.js
proposal for #254
configurable in the `livereveal` metadata with the `auto_select` flag that can be either
* `"none"` (default) - current behaviour
* `"first"` selects first cell in slide
* `"code"` selects first code cell in slide
> new feature autoselect - based on Damian's first stab

- rise/static/main.js
here's a first rough implementation for #292 
I'm calling it smart exec; it's bound to shift-enter, and allows to execute the current cell and then proceed to the next cell when the context permits
as of this code there is no config flag yet, at this point it is more a base for discussion
> Smart exec

- doc/usage.rst
Just a complement for #295.
cc @parmentelat, if you have comments feel free to add them even if you see this merged, I will take care of that in the next iteration. Thanks.
> Add a little bit of docs for smart-exec

- doc/customize.rst
- examples/header-footer.css
Finishing up #296.
cc @parmentelat
> Add pr 296

- rise/static/main.js
I figured, if we dont do this now, we wont :)
I have done this as carefully as possible, but have still no way to actually test this.
I have not changed the code at all except for formatting
It makes a huge amount of changes, but if you ignore whitespaces it's quite reasonable to review.
Please let me know if you plan on accepting this or not (no worries if not, I understand it's quite intrusive), and if yes on what sort of timeline.
> now is maybe a right time to fix #293

- rise/static/main.js
set defaults as per #321:
start_slideshow_at: 'selected',
auto_select: 'code',
> an implementation for #321

- doc/index.rst
Pushed gif to master in recent commit.
> Add basic usage gif

- doc/changelog.rst
- doc/customize.rst
- doc/installation.rst
- doc/usage.rst
Fixes #127, #178, #207, and #268.
> WIP - Several docs fixes and enhancements

- rise/static/main.js
I have not been able to test this thoroughly yet.
> hopefully closes #371

- doc/exportpdf.rst
> Some doc fixes

- README.md
Conda channel has moved to conda-forge
> Updates channel to conda-forge

- doc/dev/release.md
please review while you are at it
no brainer I guess, it's better than before and won't break the code :-)
> hopefully this would take care of #452

- src/less/main.less
> Fix x-scrolling bar in markdown cells containing code

- plugin/notes/notes.html
- plugin/notes/package.json
> fix for #456

- README.md
- setup.py
Ensure that `pip install RISE` just works. Fix #440
> Install the nbextension as part of "pip install"

- README.md
- doc/conf.py
- doc/dev/release.md
- doc/installation.rst
Just what the title says... merging now.
> Docs update towards the upcoming release

- doc/installation.rst
> Fix formatting in installation.rst

- doc/customize.md
- doc/dev/release.md
- doc/installation.rst
- doc/usage.md
- examples/README.ipynb
- src/less/main.less
> Fix some typos and examples, add more docs, fix margin-bottom css

- doc/changelog.rst
- package.json
Bump version and add the corresponding changelog.
> Release 5.5.0

- doc/changelog.rst
> Fix changelog formatting and add missed line about 5.5.0 release

- README.md
> Update link to the developer documentation

- rise/static/main.js
> load css through a relative url

- doc/usage.md
Clarified what a **notes** cell is.
(I'm trying to learn to use RISE and while doing so I stumble on some things in the documentation that I thought could be nice to clarify for newbies like me... ;) )
> Clarify in doc (there is a Slide Type called **Notes**)

- classic/src/less/main.less
> RISE with blue hyperlinks.

- doc/exportpdf.md
This can be useful when generating a pdf of a slideshow on CI
> add alternative command-line Chome pdf export to docs
