- livereveal/main.css
- livereveal/main.js
- livereveal/reset_reveal.css
This makes changes so that the following notebook:
now looks like this when using the live reveal plugin on IPython master:
> Make reveal work with new notebook layout

- livereveal/main.js
This keeps the special handling for the first and last cells, but now it finds the first and last *visible* cell (visible = not skip or notes), so you can have a skipped cell at the beginning.
Closes gh-29
> Allow cells at beginning and end to be notes/skip

- livereveal/main.js
live_real did not work for me. My IPython notebook is ver 2.31 bundled in Ubuntu 14.04 (apt-get version).
I check the javascript console and find out an error caused by `IPython.menu._size_header` not defined. After I commented out these line, live_real seems to work fine. 
So I add a check to see whether `IPython.menu._size_header` is defined before calling it.
> Ubuntu 14.04 IPython notebook does not have IPython.menu._size_header

- livereveal/main.css
- livereveal/main.js
Gets rid of metadata.internals, (slide|subslide|fragment)_helper, and several loops.
There's still some work to do - I think the behaviour of fragments is probably wrong at present. I will look into this this afternoon.
> WIP - Rewrite code to build reveal.js HTML structure

- README.md
- livereveal/main.js
- setup.py
Another significant change, but not such a big diff as the last one. This uses the new frontend config system to store user preferences, rather than putting them in custom.js where the extension is loaded.
This has the great advantage that it allows livereveal to be loaded as a regular extension, which allows the installation code to be much simpler. The new installation code will fail with an ImportError on IPython 2.x, rather than installing something that won't work.
N.B. Any users who have symlinked the extension using `setup.py install --develop` will need to reinstall it after this change, because the call to `livereveal.parameters()` in their custom.js won't work.
Addresses #55
> Use frontend config

- livereveal/main.css
When you have a slide with section names, such as
contents...
the notebook displays an anchor link `¶` at the end of section name, so that you can easily link between sections.
I see no point in showing this anchor link in presentation mode: it is distracting every time the mouse passes over it, and it does not even work (clicking it moves you to the start of the presentation).
How about hiding it?
> Hide anchor links

- README.md
- livereveal/main.js
Slideshows start at the beginning by default, but by setting a config option, you can make them start at the slide containing the currently selected cell.
Closes #66
> Config for where the slideshow starts

- README.md
The default constructor to ConfigManager refers to the default profile.
This adjusts the readme to use the active profile in ipython.  No further
comments on profiles were added as I felt these would be distracting.
Closes #88
> Adjust docs to be more profile-aware.

- livereveal/reset_reveal.css
I'm working on a presentation where I embed some tikz code that is converted to SVG by tikzmagic.  The SVG is inserted using an iframe to work around [some issues with glyphs](http://python.6.x6.nabble.com/Problems-with-tikzmagic-and-svg-output-td5075252.html).  Unfortunately the `reset_reveal.css` style restricts the size of the iframe to 95% of its size, causing unwelcome scrollbars to appear only in reveal mode:
Removing this CSS entry fixes it.  The size of the iframe is already constrained by the notebook itself anyway.
> Do not restrict the size of iframes otherwise we get a scrolbar

- livereveal/main.css
I'm using RISE for interactive presentation, but the presentation is not about Python and I don't want to show any Python code.  Instead I use widgets for interactive input/output, and hide all the python code.
Unfortunately it seems the size of the text appearing in the widgets is hard-coded in the notebook style, and it is too small for a presentation.  There is also an issue with drop-down menus, because Reveal.js setups some left indentation for all `<ul>` elements.
Here are two screenshots taken in presentation mode, before and after the patch.
Before:
After:
> Fix size of texts in Button, Text, and Dropdown widgets.

- livereveal/main.css
Looking into why I have some frame displayed around my Markdown cells in presentation mode (see picture below), I realize that 67c92cc did not completely solve #39.
In a notebook, markdown cells are not framed unless the cell toolbox is active.  So if we hide the cell toolbox, we should also hide the frame.
> hide the cell toolbox frame

- livereveal/reset_reveal.css
The notebook already has one, and the definition that was in reset_reveal.css
also conflicts with any user style.
This fixes #82.
> do not define a style for table elements

- livereveal/main.js
This fix some odd bug that has bothered me since I've started using RISE.  Typically, at some point after moving back from presentation mode and moving my navigator between different screens, I would get something like this:
The height of the notebook container (the white rectangle in the background) is smaller than the notebook itself, preventing me from scrolling further down.  Whenever I hit this situation, I had to reload the page to fix it.
Today I've realized I can reliably reproduce the issue as follows:
1. prepare a notebook that is longer than the height of your screen
2. switch to presentation mode
3. switch back to notebook mode
4. resize your browser to a small window
5. enlarge the window again
It turns out the issue comes from event listeners installed by Reveal to detect …
> remove Reveal's event listeners on exit

- livereveal/main.js
Implements #123, which enables use of RISE on any running Jupyter notebook via a bookmarklet.
Drag this _temporary_ gh-pages link (I'll take it down once there is a plan for permanent hosting) to the browser's bookmark bar.
```javascript
javascript:require(["//bollwyvl.github.io/live_reveal/livereveal/main.js"], function(r){r();});
```
I like testing it on `try.jupyter.org`, as all of my local stuff is polluted with development. You just click it, and the button shows up, hooray! Science bless `require`! I made `setup` a pun for `load_ipython_extension`, so the returned object is callable and less API-leaky.
On `gh-pages`, the bookmarklet gets served up all gzipped, CDNed and lovely, with the proper headers, over HTTPS, and [other](http://nytimes.github.io/svg-crowbar/) …
> Bookmarkletability

- setup.py
Some imports update and get rid of the profile concept and use a JUPYTER_CONFIG_DIR intead...
This should be merged after releasing the 3.x version, which should happen ASAP...
> Update to make it work with the Jupyter notebook.

- .gitignore
- README.md
- livereveal/main.css
- livereveal/main.js
- livereveal/main.orig.css
- package.json
- src/less/main.less
Jumping between slide and notebook modes is a little jarring.
This adds some transitions, maybe too many, to the transition between the modes.
> screenshot
To achieve this, it needs a few things:
- the styles have to be loaded when modes change: this means the CSS has to be added prior to switching modes, and has to be there when you leave...
- thus, the styles get added at extension setup time...
- to keep the styles from firing all the time against important elements like `#site`, the `body` is given a `rise-enabled` class, and all of the styles are conditional off being inside that
- to do this, I have ported the CSS to LESS rather than putting `.rise-enabled` in front of every directive
- this also shortens the code some, as CSS not directly manipulated by reveal can be done in CSS
I …
> Mode transitions, LESS

- README.md
- setup.py
It was changing the config in the wrong directory - see jupyter/notebook#251 for details.
If people want to install with different config directories, they should set the JUPYTER_CONFIG_DIR environment variable. ConfigManager will respect this automatically, without you needing to do anything.
i.e. instead of `python setup.py install --jupyter-config-dir foo/`, get people to do:
JUPYTER_CONFIG_DIR=foo/ python setup.py install
> Don't explicitly supply config dir to enable extension

- livereveal/main.js
Fixes #138 
ping @swnesbitt, @jorisvandenbossche 
to enable it, you need to have:
```shell
damian-S400CA :: ~/.jupyter/nbconfig :: 
$ pwd
/home/damian/.jupyter/nbconfig
damian-S400CA :: ~/.jupyter/nbconfig :: 
$ cat livereveal.json 
{
"scroll": true
}
```
> Add config option to scrolling slides.

- livereveal/main.js
Ping
@mcrovella @ndawe
Finally have a clue about what was happening with this comment... https://github.com/damianavila/RISE/issues/145#issuecomment-145294598
Please test it and report back... this fix the issue for me.
> Workaround to remove extra fade class when using fade transition

- livereveal/main.js
The names of the shortcut actions changed.
c.f. https://github.com/jupyter/notebook/issues/887
> BUG: Fix broken shortcuts in notebook 4.1.

- rise/static/main.css
- rise/static/main.js
Closes #188  
This makes Reveal.js to vertically center slides considering outputs generated on the fly.
> Closes #188: calling Reveal.sync after output is generated

- rise/static/main.js
This is better that the workaround proposed in #258.
Use promise value in the case we try to catch config outside the Revealer, where the config is actually get correctly just because the require-induced delay.
> Alternative to pr/258 config fix

- rise/static/main.js
Add z-index to CSS of help and exit buttons so that they are always in the foreground, as suggested in https://github.com/damianavila/RISE/issues/233
Before:
After:
Of course it is a question of preference, except that if you do not set the `z-index` of the buttons, they will be rendered behind the cells of code, but in front of the rendered markdown, which is not very consistent...
> Set help and exit buttons in foreground with z-index

- rise/static/main.js
The `center` option was simply omitted from `Reveal.configure()`, and thus had no effect in the notebook metadata or `ConfigManager.update()`.
> Pass the "center" option to Reveal.configure() (#166)

- rise/static/main.js
@yuvipanda and I were discussing this today and it didn't seem like it'd take too much code to support auto-launching with metadata.
This is a small patch to add an `autolaunch` metadata parameter, and an extra check at the end of `setup()` that checks for this param and launches RISE if it is `true`.
I'm submitting the PR without testing this extensively to get some feedback on whether this seems like it'll work to you...if so, lemme know what else you think should be added and I can try it out more extensively.
> adding autolaunch

- package.json
npm run reset-reveal
as per the development guide
https://github.com/damianavila/RISE#development
this was touched on in #282
> fix for correct invokation of sed on the MAC platform when running

- doc/conf.py
This PR adds a title, description, repo badge to the docs sidebar. The sidebar persists on all pages.
Congrats on the new release @damianavila :tada:
> Add consistent sidebar for all doc pages

- rise/static/main.js
Fixes the problem outlined here: https://github.com/binder-examples/jupyter-rise/issues/1
cc @choldgraf
> Make the output observer aware of the scrolling needs

- doc/usage.rst
On [this page](https://damianavila.github.io/RISE/usage.html)
| Before | After |
|:--------:|:-------:|
| ![before](https://user-images.githubusercontent.com/11994719/35737394-9cae2e8c-082b-11e8-8ddd-25e57687ff9f.png) | ![after](https://user-images.githubusercontent.com/11994719/35737405-a3b289e4-082b-11e8-97b2-e7187469929a.png) |
> Typo in usage.rst doc (list was not correctly displayed)

- MANIFEST.in
- rise.json
- setup.py
This will enable rise for notebook >= 5.3. I do see a 404 for rise.css, i'm not sure that is ok.
> auto enable nbextension when installing with pip

- doc/customize.md
- rise/static/main.js
- rise/static/rise.yaml
* define action RISE:rise-nbconfigurator
* bind it by default to shift-c
* corresponding addition in rise.yaml
* as well as in customization doc
* also contains one remaining change in the doc about toggle-note vs toggle-notes
> patch to address #358 - (together with a micro-change that belongs in #371)

- rise/static/main.js
for turning off `?` from the keyboard, that was unconditionally bound to the internal reveal help page
> a fix for #354

- setup.py
We cannot have two `>=` I'm guessing that python is only evaluating the last one making this impossible to install on `2.7`.
> Fix python_requires

- setup.cfg
The license requires that all copies of the software include the license.  This makes sure the license is included in the wheels.  See the wheel documentation [here](https://wheel.readthedocs.io/en/stable/#including-the-license-in-the-generated-wheel-file) for more information.
> Include LICENSE.md file in wheels

- package.json
- plugin/notes/index.js
- plugin/notes/notes.html
- plugin/notes/notes.js
- plugin/notes/package.json
- rise/static/main.js
This PR enable speaker notes in RISE.
We just needed to customize the notes plugin (published as an npm package) to look properly for the `notes.js` file and to configure properly the open keyboard event (to avoid overriding jupyter `s` event) and we also needed to configure it properly in main.js (as the reveal.js docs suggested).
Finally we modified the autoLaunch function to launch the presentation view when you are in the speaker notes view.
Closes #174
> Speaker notes working now

- doc/customize.md
- doc/dev/develop.md
- doc/usage.md
- examples/README.css
- examples/README.ipynb
- examples/header-footer.ipynb
- examples/overlay.ipynb
- examples/rise.css
- examples/showflow.ipynb
- package.json
- rise/static/main.js
- rise/static/rise.yaml
- src/less/main.less
review - hopefully - all places that relate to keyboard shortcut definitions
new scheme is to use - with Shift modifier:
* I for slIde
* B for suBslide
* G for fraGment
* C for Configurator - this still requires setting up nbextensions configurator
finally, there was a typo where 'note' was mentioned instead of 'notes', which
should make toggle-notes now work as expected
> close #434

- examples/rise.css
- rise/static/main.js
use jquery remove() to remove these 2 <link> elements, at the same time as the reveal material is removed as well
and  in the mix, adopting a more sensible naming scheme for these 2 <link> elements
this is entirely untested
> attempt at fixing #462

- examples/rise.css
- package.json
- patch-reveal/patch-reveal-themes.sh
- rise/static/main.js
- src/less/main.less
this is WIP and not working; most obvious broken feature at this point is themes, and more specifically theme backgrounds, that do not render as expected
I'm exposing this so that others can experiment with and feedback about an angle that I think may be worth fiddling with
in a nutshell: as mentioned a few times in some other issues like #435 and #438, when running a RISE slideshow we primarily enable 3 source of css styling: jupyter, RISE and reveal
the way reveal themes are implemented for example sets attributes on `body` which tends to potentially have rather devastating effects
the angle I have taken in this one-line approach is to monkey-patch the official reveal themes (as downloaded after `npm install`) so as to make their `body` css rule more specific, and to give them a chance …
> Reveal 3.8.0

- rise/static/main.js
This resolves #505 by passing chalkboard settings to reveal if the chalkboard is enabled and the settings are present in `rise.json`.
> Pass chalkboard options to reveal.

- doc/customize.md
- rise/static/main.js
- rise/static/rise.yaml
Hi,
I have added some code to customize the keyboard short cuts for the chalkboard (as most of the hard wired default keys are not available on my german keyboard).
I guess this is not the perfect solution (read the discussion in #442), but it allows using some custom hotkey fields in nbconfig and converts the key-strings into key codes, which are then passed to the RevealChalkboard setup (could be used for other reveal.js keys as well, I guess...).
Conversion is done by a pretty simple string concatenation of the nbconfig key-shortcut string(s) to KeyEvent's VirtualKeyboardConstants (DOM_VK_...) - falls back to the default key codes, if no match is found.
I also added some code for updating the Rise help accordingly - so the help menu should always show the user defined shortcuts (if …
> custom chalkboard key config added (main.js + rise.yaml)

- doc/customize.md
- rise/static/main.js
- rise/static/rise.yaml
After struggling to get all the special characters working with the DOM virtual keyboard constants approach for the custom keys (as I used for PR #525 ) and then having to realize that this isn't supported in google-chrome at all - I finally had a look at registering the key bindings directly in jupyter and it was actually pretty easy.
So here is a new PR based on having all the stuff set up in jupyter directly, which makes the whole thing much more robust and intuitive I would say. It also solves certain issues of the previous approach - like key combinations can now be used and you should be able to use every key in RISE you can type into the nbextension_configurator.
I had to add one hard-wired shortcut though. Jupyter does not allow to bind anything to "," (comma). And because the API …
> reveal.js/chalkboard API calls registered directly to jupyter shortcuts

- classic/rise/static/main.js
- rise-reveal/package.json
- rise-reveal/patch-chalkboard.sh
reveal.js-plugins added color support to chalkboard some time ago.
This PR moves reveal.js from 3.8.0 to 3.9.0 and imports chalkboard from the last stable v3 reveal-js.plugins
Two keys are binded to color cycling : I choose Q & S on my AZERTY keyboard but there are certainly better options.
> Adding color support to chalkboard

- doc/customize.md
Hello there,
Thanks again for this wonderful project, I just love it :clap:!
When browsing through [this page of the doc](https://rise.readthedocs.io/en/stable/usage.html#jupyterlab), I just saw a typo in Markdown markup:
This one-bit pull-request solves this typo.
Regards from France, -- @Naereen
> Update customize.md: typo `RISE/examples/header-footer.ipynb`` had extra `

- doc/customize.md
Thanks for this excellent project!
I'm in the process of starting a new presentation with RISE and was curious to experiment with the different built-in theme options. I looked around in the docs and didn't see any listing of the built-in themes, so I thought adding a link to the reveal.js theme page might be useful.
FWIW I ended up finding this info by `grep`ing for "sky" and finding `tests/themes/redo-all.sh`, which gave me an idea of what was supported (and what to search for to get more info).
> DOC: Add link to improve theme discoverability.

- classic/package.json
- classic/rise/static/main.js
- classic/src/less/main.less
- examples/header-footer-scroll.css
- examples/header-footer-scroll.ipynb
when scroll is selected, no longer hard-wire a height for the scroll area
instead, set a class on those elements, that are default-styled in main.less
but can be easily overridden by users in their CSS
this commit comes with a new example notebook named `header-footer-scroll` that illustrates how to leverage this change
> attempt to fix issue #610

- doc/customize.md
RISE does actually support passing through "center" to reveal.js but the docs don't say it's one of the supported options. This PR adds it to the docs.
> Add center to documentation

- classic/rise/static/rise.yaml
Currently the `sync_timeout` argument cannot be properly configured because it is mistakenly called `aync_timeout` in the config.
> Fix sync_timeout parameter
